[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = [
  "E203",  # Whitespace before ':'
  "E501",  # Line too long
]

[tool.ruff.lint.isort]
known-first-party = ["app"]
combine-as-imports = true

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
no_strict_optional = true
check_untyped_defs = true
disallow_untyped_defs = false

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
  "tests",
]
python_files = [
  "test_*.py",
  "*_test.py",
]
