[tool.ruff]
target-version = "py311"
line-length = 100

lint.select = ["E", "F", "W", "I"]
lint.ignore = ["E203", "E501"]  # optional: reduce noise


# Enable common linting rules (errors, warnings, imports)
lint.select = ["E", "F", "W", "I"]

# Ignore some rules that cause noise
lint.ignore = [
  "E203",  # Whitespace before ':'
  "E501",  # Line too long (we let plot labels be long)
]
