[tool.ruff]
line-length = 100
target-version = "py311"

# Enable common linting rules (errors, warnings, imports)
select = ["E", "F", "W", "I"]

# Ignore some rules that cause noise
ignore = [
  "E203",  # Whitespace before ':'
  "E501",  # Line too long (we let plot labels be long)
]

[tool.ruff.isort]
known-first-party = ["app"]
combine-as-imports = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
  "tests",
]
python_files = [
  "test_*.py",
  "*_test.py",
]
